const defaultContent = {
	root: {
		children: [
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Agora",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h1",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "The agora (",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "/ˈæɡərə/",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Help:IPA/English",
						url: "https://en.wikipedia.org/wiki/Help:IPA/English",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "; ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Ancient Greek",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Ancient Greek language",
						url: "https://en.wikipedia.org/wiki/Ancient_Greek_language",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ': ἀγορά,romanized:agorá, meaning "market" in ',
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Modern Greek",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Modern Greek",
						url: "https://en.wikipedia.org/wiki/Modern_Greek",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ") was a central ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "public space",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Public space",
						url: "https://en.wikipedia.org/wiki/Public_space",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " in ancient ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Greek",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Ancient Greece",
						url: "https://en.wikipedia.org/wiki/Ancient_Greece",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "city-states",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Polis",
						url: "https://en.wikipedia.org/wiki/Polis",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ". It is the best representation of a city-state's response to accommodate the social and political order of the polis.",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[1]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-1",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ' The literal meaning of the word "agora" is "gathering place" or "assembly". The agora was the center of the athletic, artistic, business, social, spiritual, and political life in the city.',
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[2]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-InternationalDictionary-2",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " The Ancient Agora of Athens is the best-known example.",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Origins",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "start",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h2",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Early in Greek history (13th–4th centuries BC), free-born citizens would gather in the agora for military duty or to hear statements of the ruling king or council. Later, the agora also served as a ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "marketplace",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Marketplace",
						url: "https://en.wikipedia.org/wiki/Marketplace",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", where merchants kept stalls or shops to sell their goods amid ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "arcades",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Arcade (architecture)",
						url: "https://en.wikipedia.org/wiki/Arcade_(architecture)",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ". This attracted ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "artisans",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Artisan",
						url: "https://en.wikipedia.org/wiki/Artisan",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " who built workshops nearby.",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[3]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-lag-3",
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: 'From these twin functions of the agora as a political and a commercial spot came the two Greek verbs ἀγοράζω, agorázō, "I shop", and ἀγορεύω, agoreúō, "I speak in public".',
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[4]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-4",
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Ancient Agora of Athens",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "start",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h2",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "The ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Ancient Agora of Athens",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Ancient Agora of Athens",
						url: "https://en.wikipedia.org/wiki/Ancient_Agora_of_Athens",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " was situated beneath the northern slope of the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Acropolis",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Acropolis of Athens",
						url: "https://en.wikipedia.org/wiki/Acropolis_of_Athens",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ". The Ancient Agora was the primary meeting ground for Athenians, where members of ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "democracy",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Democracy",
						url: "https://en.wikipedia.org/wiki/Democracy",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " congregated affairs of the state, where business was conducted, a place to hang out, and watch performers and listen to famous ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "philosophers",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Philosopher",
						url: "https://en.wikipedia.org/wiki/Philosopher",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ". The importance of the Athenian agora revolved around religion. The agora was a very sacred place, in which holiness is laid out in the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "architecture",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Architecture",
						url: "https://en.wikipedia.org/wiki/Architecture",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " of the ground upon which it lay upon. The layout of the agora was centered around the Panathenaic Way, a road that ran through the middle of ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Athens",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Athens",
						url: "https://en.wikipedia.org/wiki/Athens",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " and to the main gate of the city, ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Dipylon",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Dipylon",
						url: "https://en.wikipedia.org/wiki/Dipylon",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ".",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[5]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-5",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " This road was considered tremendously sacred, serving as a travel route for the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Panathenaic festival",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Panathenaic Games",
						url: "https://en.wikipedia.org/wiki/Panathenaic_Games",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", which was held in honor of the goddess ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Athena",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Athena",
						url: "https://en.wikipedia.org/wiki/Athena",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " every four years. The agora was also famously known for housing the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Temple of Hephaestus",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Temple of Hephaestus",
						url: "https://en.wikipedia.org/wiki/Temple_of_Hephaestus",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", the Greek god of metalworking and craftsmen. This temple is still in great condition to this day. Other temples priorly standing in the agora include honor for ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Zeus",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Zeus",
						url: "https://en.wikipedia.org/wiki/Zeus",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Athena",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Athena",
						url: "https://en.wikipedia.org/wiki/Athena",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Apollo",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Apollo",
						url: "https://en.wikipedia.org/wiki/Apollo",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", and ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Ares",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Ares",
						url: "https://en.wikipedia.org/wiki/Ares",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ".",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[6]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-6",
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Location and constituents",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "start",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h2",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "The agora was usually located in the middle of a city or near the harbor. Agoras were built of ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "colonnades",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Colonnade",
						url: "https://en.wikipedia.org/wiki/Colonnade",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", or rows of long columns, and contained ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "stoae",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Stoa",
						url: "https://en.wikipedia.org/wiki/Stoa",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", also known as a long open walkway below the colonnades.",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[7]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-7",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " They were beautifully decorated with fountains, trees, and statues. When the Athenian agora was rebuilt after the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Greco-Persian Wars",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Greco-Persian Wars",
						url: "https://en.wikipedia.org/wiki/Greco-Persian_Wars",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", colonnades and stoae were not incorporated.",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 64,
								mode: "normal",
								style: "",
								text: "[8]",
								type: "text",
								version: 1,
							},
						],
						direction: null,
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: null,
						url: "https://en.wikipedia.org/wiki/Agora#cite_note-8",
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Phobia",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "start",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h2",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "The term ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "agoraphobia",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: null,
						target: null,
						title: "Agoraphobia",
						url: "https://en.wikipedia.org/wiki/Agoraphobia",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " denotes a phobic condition in which the sufferer becomes anxious in unfamiliar environments – for instance, places where they perceive that they have little control. Such anxiety may be triggered by wide-open spaces, crowds, or public situations, and the psychological term derives from the agora as a large and open gathering place.",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "start",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
		],
		direction: "ltr",
		format: "",
		indent: 0,
		type: "root",
		version: 1,
	},
};
export const loadContent = JSON.stringify(defaultContent);
