const defaultContent = {
	root: {
		children: [
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Hey there,",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h1",
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Rewrite is a Notion-style WYSIWYG editor. Built with ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Lexical",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: "noopener noreferrer nofollow",
						target: "_blank",
						title: null,
						url: "https://lexical.dev/",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "OpenAI",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: "noopener noreferrer nofollow",
						target: "_blank",
						title: null,
						url: "https://openai.com/",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ", and the ",
						type: "text",
						version: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Vercel AI SDK",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "link",
						version: 1,
						rel: "noopener noreferrer nofollow",
						target: "_blank",
						title: null,
						url: "https://sdk.vercel.ai/docs",
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: " → ",
						type: "text",
						version: 1,
					},
					{
						detail: 0,
						format: 16,
						mode: "normal",
						style: "",
						text: "npm i ai",
						type: "text",
						version: 1,
					},
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: ".",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "paragraph",
				version: 1,
			},
			{
				children: [
					{
						detail: 0,
						format: 0,
						mode: "normal",
						style: "",
						text: "Learn more",
						type: "text",
						version: 1,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "heading",
				version: 1,
				tag: "h3",
			},
			{
				children: [
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Check out the ",
								type: "text",
								version: 1,
							},
							{
								children: [
									{
										detail: 0,
										format: 0,
										mode: "normal",
										style: "",
										text: "playground",
										type: "text",
										version: 1,
									},
								],
								direction: "ltr",
								format: "",
								indent: 0,
								type: "link",
								version: 1,
								rel: "noopener noreferrer nofollow",
								target: "_blank",
								title: null,
								url: "https://playground.lexical.dev",
							},
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: ".",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "listitem",
						version: 1,
						value: 1,
					},
					{
						children: [
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: "Star us on ",
								type: "text",
								version: 1,
							},
							{
								children: [
									{
										detail: 0,
										format: 0,
										mode: "normal",
										style: "",
										text: "GitHub",
										type: "text",
										version: 1,
									},
								],
								direction: "ltr",
								format: "",
								indent: 0,
								type: "link",
								version: 1,
								rel: "noopener noreferrer nofollow",
								target: "_blank",
								title: null,
								url: "https://github.com/facebook/lexical",
							},
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: ".",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "listitem",
						version: 1,
						value: 2,
					},
					{
						children: [
							{
								children: [
									{
										detail: 0,
										format: 0,
										mode: "normal",
										style: "",
										text: "Deploy",
										type: "text",
										version: 1,
									},
								],
								direction: "ltr",
								format: "",
								indent: 0,
								type: "link",
								version: 1,
								rel: "noopener noreferrer nofollow",
								target: "_blank",
								title: null,
								url: "https://vercel.com/templates/next.js/novel",
							},
							{
								detail: 0,
								format: 0,
								mode: "normal",
								style: "",
								text: " your own.",
								type: "text",
								version: 1,
							},
						],
						direction: "ltr",
						format: "",
						indent: 0,
						type: "listitem",
						version: 1,
						value: 3,
					},
				],
				direction: "ltr",
				format: "",
				indent: 0,
				type: "list",
				version: 1,
				listType: "number",
				start: 1,
				tag: "ol",
			},
		],
		direction: "ltr",
		format: "",
		indent: 0,
		type: "root",
		version: 1,
	},
};
export const loadContent = JSON.stringify(defaultContent);
